name: Tests

on: [push, pull_request]

jobs:

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: src/datasources
        snakefile: src/datasources/workflow/Snakefile
        args: "--lint"
        stagein: >-
          python -m pip install --no-deps .

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v4
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: src/datasources/.test
        snakefile: src/datasources/workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache"
        stagein: >-
          python -m pip install --no-deps .

  Test-cli:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [7, 8]
        python-version: [3.11]
    defaults:
      run:
        shell: bash -l {0}  # a login shell is required for conda activation
    steps:
    - uses: actions/checkout@v4
    - name: Create conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        mamba-version: "*"
        channels: conda-forge,bioconda,default
        python-version: ${{ matrix.python-version }}
    - name: List repo
      run: |
        conda env list
        conda list
    - name: Install repo
      run: python -m pip install --no-deps .
    - name: Install snakemake
      run: |
        mamba install snakemake=${{ matrix.version }} numpy
    - name: Test workflow with datasources cli (local test data)
      run: datasources run --directory src/datasources/.test --show-failed-logs -j 2 --conda-cleanup-pkgs cache

