name: Tests

on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: src/datasources
        snakefile: src/datasources/workflow/Snakefile
        args: "--lint"
        stagein: >-
          python -m pip install --no-deps .

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v2
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: src/datasources/.test
        snakefile: src/datasources/workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache"
        stagein: >-
          python -m pip install --no-deps .

  Test-cli:
    runs-on: ubuntu-latest
    needs: Linting
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Install repo
        run: python -m pip install --no-deps .
      - name: Test workflow with datasources cli (local test data)
        run: datasources run --directory src/datasources/.test --show-failed-logs -j 2 --conda-cleanup-pkgs cache
