name: Tests

on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: src/datasources
        snakefile: src/datasources/workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v2
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .test
        snakefile: src/datasources/workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache --conda-frontend mamba"
