name: Tests

on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: src/datasources
        snakefile: src/datasources/workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v2
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .test
        snakefile: src/datasources/workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 2 --conda-cleanup-pkgs cache"

  Test-cli:
    runs-on: ubuntu-latest
    needs: Linting
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Test workflow with datasources cli (local test data)
        run: datasources run --directory .test --show-failed-logs -j 2 --conda-cleanup-pkgs cache
